name: Lint
on: [ push, pull_request ]
jobs:
    quality-tools:
        name: Run PHP-CS-Fixer & PHPStan
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4

            -   name: Install dependencies
                run: composer install --no-progress --prefer-dist --optimize-autoloader

            -   name: PHP-CS-Fixer
                run: ./bin/php-cs-fixer --diff --dry-run

            -   name: PHPStan Static Analysis
                run: ./bin/phpstan
